require('dotenv').config();
const mongoose = require('mongoose');
const LandRegistry = require('../models/LandRegistry');

const landRegistryData = [
    {
        parcelNumber: "LOC/1234/567",
        ownerName: "JOHN KAMAU MWANGI",
        county: "Nairobi City County",
        area: "0.045",
        titleNumber: "NRB/WEST/7834/IR",
        dateIssued: "15/03/2021",
        landUse: "Residential",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: true,
    },
    {
        parcelNumber: "LOC/5678/001",
        ownerName: "FRANCIS AUKA",
        county: "Nairobi City County",
        area: "0.045",
        titleNumber: "NRB/WEST/5678/IR",
        dateIssued: "03/06/2022",
        landUse: "Residential",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: true,
    },
    {
        parcelNumber: "LOC/3344/112",
        ownerName: "GREGORY AUKA",
        county: "Nairobi City County",
        area: "0.045",
        titleNumber: "NRB/WEST/3344/IR",
        dateIssued: "11/01/2023",
        landUse: "Residential",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: true,
    },
    {
        parcelNumber: "LOC/9999/001",
        ownerName: "JOHN KAMAU MWANGI",
        county: "Nairobi City County",
        area: "0.052",
        titleNumber: "NRB/WEST/9999/IR",
        dateIssued: "22/08/2023",
        landUse: "Commercial",
        tenure: "Leasehold — 99 Years from 1st January 2000",
        status: "active",
        registeredOnTitleGuard: true,
    },
    {
        parcelNumber: "LOC/9999/002",
        ownerName: "FRANCIS AUKA",
        county: "Nairobi City County",
        area: "0.045",
        titleNumber: "NRB/WEST/9999/2IR",
        dateIssued: "03/06/2022",
        landUse: "Residential",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: true,
    },
    {
        parcelNumber: "LOC/2200/045",
        ownerName: "MARY WANJIKU NJOROGE",
        county: "Nairobi City County",
        area: "0.030",
        titleNumber: "NRB/KIL/2200/IR",
        dateIssued: "07/02/2020",
        landUse: "Residential",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: true,
    },
    {
        parcelNumber: "LOC/4410/223",
        ownerName: "PETER OTIENO ODHIAMBO",
        county: "Mombasa County",
        area: "0.060",
        titleNumber: "MSA/NYL/4410/IR",
        dateIssued: "14/05/2019",
        landUse: "Residential",
        tenure: "Leasehold — 99 Years from 1st June 1999",
        status: "active",
        registeredOnTitleGuard: true,
    },
    {
        parcelNumber: "LOC/6621/089",
        ownerName: "GRACE MUTHONI KAMAU",
        county: "Kisumu County",
        area: "0.025",
        titleNumber: "KSM/MIG/6621/IR",
        dateIssued: "19/10/2021",
        landUse: "Commercial",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: true,
    },
    {
        parcelNumber: "LOC/1100/334",
        ownerName: "SAMUEL KIBET RONO",
        county: "Uasin Gishu County",
        area: "0.080",
        titleNumber: "ELD/UAS/1100/IR",
        dateIssued: "02/03/2018",
        landUse: "Commercial",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/7734/201",
        ownerName: "JANE ACHIENG OUMA",
        county: "Kisumu County",
        area: "0.035",
        titleNumber: "KSM/KIS/7734/IR",
        dateIssued: "25/07/2020",
        landUse: "Commercial",
        tenure: "Leasehold — 99 Years from 1st January 2000",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/3310/567",
        ownerName: "DAVID MUTUA MWENDE",
        county: "Machakos County",
        area: "0.100",
        titleNumber: "MBS/MBS/3310/IR",
        dateIssued: "08/11/2017",
        landUse: "Agricultural",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/8821/003",
        ownerName: "ESTHER WAMBUA NZOMO",
        county: "Nakuru County",
        area: "0.055",
        titleNumber: "NKR/NKR/8821/IR",
        dateIssued: "30/04/2016",
        landUse: "Residential",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/5500/178",
        ownerName: "HASSAN OMAR FARAJ",
        county: "Mombasa County",
        area: "0.020",
        titleNumber: "MSA/MSA/5500/IR",
        dateIssued: "12/12/2019",
        landUse: "Commercial",
        tenure: "Leasehold — 99 Years from 1st January 1990",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/2987/445",
        ownerName: "ALICE CHEBET SANG",
        county: "Nandi County",
        area: "0.040",
        titleNumber: "ELD/KAP/2987/IR",
        dateIssued: "05/08/2021",
        landUse: "Residential",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/6003/290",
        ownerName: "JAMES KARIUKI NJUGUNA",
        county: "Nyeri County",
        area: "0.070",
        titleNumber: "NYR/NYR/6003/IR",
        dateIssued: "18/02/2022",
        landUse: "Residential",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/4456/112",
        ownerName: "BEATRICE ATIENO ODONGO",
        county: "Homa Bay County",
        area: "0.090",
        titleNumber: "HOM/HOM/4456/IR",
        dateIssued: "09/09/2015",
        landUse: "Agricultural",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/9102/678",
        ownerName: "MICHAEL NJOROGE GACHERU",
        county: "Nairobi City County",
        area: "0.048",
        titleNumber: "NBI/KAS/9102/IR",
        dateIssued: "01/03/2024",
        landUse: "Residential",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/3781/056",
        ownerName: "FATUMA ALI MOHAMMED",
        county: "Kilifi County",
        area: "0.065",
        titleNumber: "MSA/KIL/3781/IR",
        dateIssued: "22/06/2018",
        landUse: "Residential",
        tenure: "Leasehold — 99 Years from 1st January 2000",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/7290/334",
        ownerName: "JOSEPH WEKESA BARASA",
        county: "Kakamega County",
        area: "0.075",
        titleNumber: "KAK/KAK/7290/IR",
        dateIssued: "14/04/2023",
        landUse: "Agricultural",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: false,
    },
    {
        parcelNumber: "LOC/1892/445",
        ownerName: "SARAH KOECH BETT",
        county: "Kirinyaga County",
        area: "0.110",
        titleNumber: "KER/KER/1892/IR",
        dateIssued: "03/01/2014",
        landUse: "Agricultural",
        tenure: "Freehold",
        status: "active",
        registeredOnTitleGuard: false,
    },
];

const seed = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('Connected to MongoDB');
        await LandRegistry.deleteMany({});
        const inserted = await LandRegistry.insertMany(landRegistryData);
        console.log(`Seeded ${inserted.length} land registry records`);
        process.exit(0);
    } catch (error) {
        console.error('Seed error:', error.message);
        process.exit(1);
    }
};

seed();
